### ISSUE TITLE
contract add: internal_server_error

### ISSUE THREAD

**Issue by bitdeep** [Tenderly/tenderly-sdk#104]
Hi, I'm trying to add contracts to my tenderly project, but I keep getting server error:

```
Tenderly: ApiError: Internal server error
    at Function.handle (contractsnode_modules\@tenderly\sdk\dist\index.js:142:13)
    at contractsnode_modules\@tenderly\sdk\dist\index.js:247:46
    at Array.forEach (<anonymous>)
    at handleError (contractsnode_modules\@tenderly\sdk\dist\index.js:247:17)
    at ContractRepository.<anonymous> (contractsnode_modules\@tenderly\sdk\dist\index.js:347:9)
    at Generator.throw (<anonymous>)
    at rejected (contractsnode_modules\@tenderly\sdk\dist\index.js:74:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  id: '50cebf37-28ec-465a-a9d1-b3b5f517df18',
  slug: 'internal_server_error',
  data: undefined,
  status: 500
}
```

- "@tenderly/sdk": "^0.2.1"
- "hardhat": "2.19.4"

**Comment by Zartaj0** [comment]
How did you solve this? I am currently facing the same error.
